const TOTAL_GLA_BY_COUNTRY_TITLE = 'Total GLA by Country'
const REVERSION_POTENTIAL_BY_COUNTRY_TITLE = 'Reversion Potential By Country Title'
const OCCUPANCY_BY_COUNTRY_TITLE = 'Occupancy By Country'
const AVERAGE_WALE_N_WALB_BY_COUNTRY_TITLE = 'Average WALE & WALB By Country'
const TENANT_SECTOR_EXPOSURE_BY_COUNTRY_TITLE = 'Tenant Sector Exposure, by Country '

export const ANALYTICS_TITLE = {
    TOTAL_GLA_BY_COUNTRY_TITLE,
    REVERSION_POTENTIAL_BY_COUNTRY_TITLE,
    OCCUPANCY_BY_COUNTRY_TITLE,
    AVERAGE_WALE_N_WALB_BY_COUNTRY_TITLE,
    TENANT_SECTOR_EXPOSURE_BY_COUNTRY_TITLE
}