import { STAGES } from '@bpd/bpd-web/shared/core'

export const EU_STATUSES = [
  STAGES.NEW_DEAL_FOR_DISCUSSION,
  STAGES.UNDER_CONSIDERATION,
  STAGES.DEALS_WITH_DQM_APPROVAL,
  STAGES.DEALS_SIGNED,
  STAGES.CLOSED,
]

export const US_STATUSES = [
  STAGES.NEW_DEAL_FOR_DISCUSSION,
  STAGES.UNDER_CONSIDERATION,
  STAGES.UNDER_CONSIDERATION_APPROVED,
  STAGES.CLOSED,
]
