export const SECTORS = {
  DATA_CENTER: 'Data Center',
  DIVERSIFIED_CANNOT_BE_BROKEN: 'Diversified (cannot be broken down)',
  EDUCATION: 'Education',
  HEALTHCARE: 'Healthcare',
  HOSPITALITY: 'Hospitality',
  INDUSTRIAL: 'Industrial',
  LIFE_SCIENCE: 'Life Science',
  MANUFACTURED_HOUSING: 'Manufactured Housing',
  OFFICE: 'Office',
  RENTAL_APARTMENT: 'Rental Apartment',
  RESIDENTIAL_FOR_SALE: 'Residential for Sale',
  RETAIL: 'Retail',
  SENIOR_HOUSING: 'Senior Housing',
  SELF_STORAGE: 'Self Storage',
  STUDENT_HOUSING: 'Student Housing',
  UNALLOCATED_ACC: 'Unallocated Acc',
  OTHERS: 'Others',
  STORAGE: 'Storage',
  RESIDENTIAL: 'Residential',
  MIXED_USE: 'Mixed Use',
  DIVERSIFIED: 'Diversified',
}
