import { ROUTES } from '@bpd/bpd-web/shared/config'

const OVERVIEW_TAB = {
  tab: 'Overview',
  key: ROUTES.DASHBOARDS.MARKET.MARKET_TRANSACTIONS.OVERVIEW,
}

const TXN_VOL_SUMMARY_TAB = {
  tab: 'Transaction Volume Summary',
  key: ROUTES.DASHBOARDS.MARKET.MARKET_TRANSACTIONS.TXN_VOL_SUMMARY,
}

const INVT_BY_SOC_TAB = {
  tab: 'Investment By Source of Capital',
  key: ROUTES.DASHBOARDS.MARKET.MARKET_TRANSACTIONS.INVT_BY_SOC,
}

const TOP_SALES_TAB = {
  tab: 'Top Sales',
  key: ROUTES.DASHBOARDS.MARKET.MARKET_TRANSACTIONS.TOP_SALES,
}

const TOP_BUYERS_SELLERS_TAB = {
  tab: 'Buyers / Sellers',
  key: ROUTES.DASHBOARDS.MARKET.MARKET_TRANSACTIONS.TOP_BUYERS_SELLERS,
}

const COMPANIES_TAB = {
  tab: 'Company',
  key: ROUTES.DASHBOARDS.MARKET.MARKET_TRANSACTIONS.COMPANIES,
}

export const TABS = {
  OVERVIEW: OVERVIEW_TAB,
  TXN_VOL_SUMMARY: TXN_VOL_SUMMARY_TAB,
  INVT_SRC_CAPITAL: INVT_BY_SOC_TAB,
  TOP_SALES: TOP_SALES_TAB,
  TOP_BUYERS_SELLERS: TOP_BUYERS_SELLERS_TAB,
  COMPANIES: COMPANIES_TAB,
}
