export { default as BASE_ROUTES } from './BASE_ROUTES'
export { default as SCOPE } from './SCOPE'
export { default as PAGE_TITLE } from './PAGE_TITLE'
export { default as VIEW_STATE } from './VIEW_STATE'
export * from './BREADCRUMBS'