environment: development

conjur:
  secretYaml: |-
    SYSTEMACCT: REPLACEME
    SYSTEMACCTPW: REPLACEME

deployments:
  REPLACEME:
    service:
      routes:
        - annotations: # any other additional annotations
            haproxy.router.openshift.io/rewrite-target: "/"
            # haproxy.router.openshift.io/disable_cookies: "true"
          targetPort: 8080 # required (either service port number or port name to expose)
    env:
    autoscaling:
      minReplicas: 4
      maxReplicas: 8
