
export interface ESGPortalRequestPayload {
    id: number,
    cartodbId: number,
    acquisitionDt: Date,
    bucket: number,
    bucketNotes: string,
    builtYear: string,
    capacity: number,
    capacityUom: string,
    countryIso: string,
    dataDt: Date,
    disposalDt: Date,
    gfa: number,
    gfaSqm: number,
    gfaUom: string,
    gicShare: number,
    greenCert: string,
    hasCaseStudy: boolean,
    hasPhoto: boolean,
    horizon: string,
    hurricane: string,
    hurricaneRr: number,
    inlandFlood: string,
    inlandFloodRr: number,
    invtEndDt: Date,
    invtStartDt: Date,
    invtVehicle: string,
    lat: number,
    lng: number,
    nvmUsd: number,
    projId: string,
    projName: string,
    projSector: string,
    propId: string,
    propMgrName: string,
    propName: string,
    propNmv: number,
    propRegion: string,
    propType: string,
    quality: string,
    stormSurge: string,
    stormSurgeRr: number,
    strategy: string,
    theGeom: string,
    theGeomWebmercator: string,
    wildfire: string,
    wildfireRr: number
}

//46