export const TAB_OVERVIEW = 'OVERVIEW'
export const TAB_RISK_ANALYSIS = 'RISK ANALYSIS'
export const TAB_MAP = 'MAP'
export const TAB_CARD = 'CARD'
export const TAB_TABLE = 'TABLE'

export const TAB = {
  OVERVIEW: TAB_OVERVIEW,
  RISK_ANALYSIS: TAB_RISK_ANALYSIS,
  MAP: TAB_MAP,
  CARD: TAB_CARD,
  TABLE: TAB_TABLE,
}
