export const COLUMN_REGION = 'propRegion'
export const COLUMN_SECTOR = 'propType'
export const COLUMN_STORM_SURGE_RISK_RATING = 'stormSurgeRr'
export const COLUMN_HURRICANE_RISK_RATING = 'hurricaneRr'
export const COLUMN_INLAND_FLOOR_RISK_RATING = 'inlandFloodRr'
export const COLUMN_WILDFIRE_RISK_RATING = 'wildfireRr'
export const COLUMN_BUCKET = 'bucket'

export const FILTER_COLUMN = {
  COLUMN_REGION,
  COLUMN_SECTOR,
  COLUMN_STORM_SURGE_RISK_RATING,
  COLUMN_HURRICANE_RISK_RATING,
  COLUMN_INLAND_FLOOR_RISK_RATING,
  COLUMN_WILDFIRE_RISK_RATING,
  COLUMN_BUCKET,
}
