import { ROUTES } from '@bpd/bpd-web/shared/config'

const DEALS_TAB = { tab: 'Deals', key: ROUTES.INVESTMENT_PROCESS.EU.DEALS }

const PEOPLE_TAB = { tab: 'People', key: ROUTES.INVESTMENT_PROCESS.EU.PEOPLE }

const PROJECTS_TAB = {
  tab: 'Projects',
  key: ROUTES.INVESTMENT_PROCESS.EU.PROJECTS,
}

const TRACKER_TAB = {
  tab: 'Tracker',
  key: ROUTES.INVESTMENT_PROCESS.EU.TRACKER,
}

const INVESTMENT_MEMO_TAB = {
  tab: 'Investment Memo',
  key: ROUTES.INVESTMENT_PROCESS.EU.INVESTMENT_MEMO,
}

export const TABS = {
  DEALS: DEALS_TAB,
  PEOPLE: PEOPLE_TAB,
  PROJECTS: PROJECTS_TAB,
  TRACKER: TRACKER_TAB,
  INVESTMENT_MEMO: INVESTMENT_MEMO_TAB,
}
