import { DEAL_REQ_TYPE } from '@bpd/ui/constants'

const NEW_INVESTMENT = DEAL_REQ_TYPE.DIRECT_INVESTMENT
const PROGRAMMATIC_JV_SUB_DEAL = DEAL_REQ_TYPE.PRGM_JV_SUB_DEAL
const ADDITIONAL_COMMITMENT = DEAL_REQ_TYPE.ADD_COMMITMENT
const DIVESTMENT = DEAL_REQ_TYPE.DIVESTMENT
const SOFT_COMMITMENT_RELEASE = DEAL_REQ_TYPE.SOFT_COMMITMENT_RELEASE
const GIPS = DEAL_REQ_TYPE.GIPS
const OTHERS = DEAL_REQ_TYPE.OTHERS

export const TYPES = {
  NEW_INVESTMENT,
  PROGRAMMATIC_JV_SUB_DEAL,
  ADDITIONAL_COMMITMENT,
  DIVESTMENT,
  SOFT_COMMITMENT_RELEASE,
  GIPS,
  OTHERS,
}
