export const MY_WORKSPACE_CONFIG_BASE = '/references/workspace-config'

export const MY_WORKSPACE_CONFIG_ENDPOINTS = {
  BASE: MY_WORKSPACE_CONFIG_BASE,
  GET_WORKSPACE_CONFIG: `${MY_WORKSPACE_CONFIG_BASE}/userid`,
}

export const ENDPOINTS = {
  MY_WORKSPACE: MY_WORKSPACE_CONFIG_ENDPOINTS,
}
