import { ROUTES } from '@bpd/bpd-web/shared/config'

const CASE_STUDY = {
  tab: 'Case Study',
  key: ROUTES.KNOWLEDGE.ESG_ADE_PORTAL.CASE_STUDY,
}

const RESEARCH = {
  tab: 'Research',
  key: ROUTES.KNOWLEDGE.ESG_ADE_PORTAL.RESEARCH,
}

const POLICIES_AND_PROCEDURES = {
  tab: 'Policies & Procedures',
  key: ROUTES.KNOWLEDGE.ESG_ADE_PORTAL.POLICIES_AND_PROCEDURES,
}

const ESG_BULLETIN = {
  tab: 'ESG Bulletin',
  key: ROUTES.KNOWLEDGE.ESG_ADE_PORTAL.ESG_BULLETIN,
}

const ESG_TALKING_POINTS_WITH_EXTERNAL_PARTIES = {
  tab: 'ESG Talking Points with External Parties',
  key: ROUTES.KNOWLEDGE.ESG_ADE_PORTAL.ESG_TALKING_POINTS_WITH_EXTERNAL_PARTIES,
}

const RED_OR_AMBER_SCREENING = {
  tab: 'Red / Amber Screening',
  key: ROUTES.KNOWLEDGE.ESG_ADE_PORTAL.RED_OR_AMBER_SCREENING,
}

const RES_APPROACH_TO_SUSTAINABILITY = {
  tab: "RE's Approach to Sustainability",
  key: ROUTES.KNOWLEDGE.ESG_ADE_PORTAL.RES_APPROACH_TO_SUSTAINABILITY,
}

export const TABS = {
  CASE_STUDY,
  RESEARCH,
  POLICIES_AND_PROCEDURES,
  ESG_BULLETIN,
  ESG_TALKING_POINTS_WITH_EXTERNAL_PARTIES,
  RED_OR_AMBER_SCREENING,
  RES_APPROACH_TO_SUSTAINABILITY,
}
