export const COMMENTS_TAG = 'COMMENTS'

export const DEALS_TAG = 'DEALS'

export const STAFF_REPORTS_TAG = 'STAFF_REPORTS'

export const TAGS = {
  COMMENTS: COMMENTS_TAG,
  DEALS: DEALS_TAG,
  STAFF_REPORTS: STAFF_REPORTS_TAG,
}
