import { uniq } from 'lodash'
import { Team } from './TEAMS'
import * as COUNTRIES from './COUNTRY_LIST'

export const DEAL_COUNTRY_LIST_BY_TEAM: Record<
  Uppercase<Partial<Team>>,
  string[]
> = {
  US: [
    COUNTRIES.UNITED_STATES,
    COUNTRIES.BRAZIL,
    COUNTRIES.MEXICO,
    COUNTRIES.CANADA,
    COUNTRIES.CARIBBEAN,
  ],
  JP: [COUNTRIES.JAPAN],
  CN: [COUNTRIES.CHINA, COUNTRIES.HONG_KONG, COUNTRIES.TAIWAN],
  ANZ: [COUNTRIES.AUSTRALIA, COUNTRIES.NEW_ZEALAND],
  EU: [
    COUNTRIES.UNITED_KINGDOM,
    COUNTRIES.GERMANY,
    COUNTRIES.FRANCE,
    COUNTRIES.ITALY,
    COUNTRIES.AUSTRIA,
    COUNTRIES.BELGIUM,
    COUNTRIES.CZECH_REPUBLIC,
    COUNTRIES.FINLAND,
    COUNTRIES.GREECE,
    COUNTRIES.HUNGARY,
    COUNTRIES.IRELAND,
    COUNTRIES.NETHERLANDS,
    COUNTRIES.NORWAY,
    COUNTRIES.POLAND,
    COUNTRIES.PORTUGAL,
    COUNTRIES.ROMANIA,
    COUNTRIES.RUSSIA_FEDERATION,
    COUNTRIES.SLOVAKIA,
    COUNTRIES.SPAIN,
    COUNTRIES.SWEDEN,
    COUNTRIES.TURKEY,
    'Multiple',
  ],
  KR: [COUNTRIES.SOUTH_KOREA],
  IN: [COUNTRIES.INDIA],
  GIPS: [
    'Global',
    'Americas',
    'Europe',
    'Asia',
    'Greater China',
    COUNTRIES.CHINA,
    COUNTRIES.HONG_KONG,
    COUNTRIES.TAIWAN,

    COUNTRIES.UNITED_STATES,
    COUNTRIES.BRAZIL,
    COUNTRIES.MEXICO,
    COUNTRIES.CANADA,
    COUNTRIES.CARIBBEAN,

    COUNTRIES.UNITED_KINGDOM,
    COUNTRIES.GERMANY,
    COUNTRIES.FRANCE,
    COUNTRIES.ITALY,
    COUNTRIES.AUSTRIA,
    COUNTRIES.BELGIUM,
    COUNTRIES.CZECH_REPUBLIC,
    COUNTRIES.FINLAND,
    COUNTRIES.GREECE,
    COUNTRIES.HUNGARY,
    COUNTRIES.IRELAND,
    COUNTRIES.NETHERLANDS,
    COUNTRIES.NORWAY,
    COUNTRIES.POLAND,
    COUNTRIES.PORTUGAL,
    COUNTRIES.ROMANIA,
    COUNTRIES.RUSSIA_FEDERATION,
    COUNTRIES.SLOVAKIA,
    COUNTRIES.SPAIN,
    COUNTRIES.SWEDEN,
    COUNTRIES.TURKEY,

    COUNTRIES.AUSTRALIA,
    COUNTRIES.NEW_ZEALAND,

    COUNTRIES.INDIA,

    COUNTRIES.JAPAN,

    COUNTRIES.SOUTH_KOREA,

    COUNTRIES.INDONESIA,
    COUNTRIES.VIETNAM,
    COUNTRIES.THAILAND,
    COUNTRIES.MALAYSIA,
    COUNTRIES.PHILIPPINES,

    COUNTRIES.MALDIVES,
  ],
  ASIG: [
    COUNTRIES.AUSTRALIA,
    COUNTRIES.NEW_ZEALAND,

    COUNTRIES.CHINA,
    COUNTRIES.HONG_KONG,
    COUNTRIES.TAIWAN,

    COUNTRIES.JAPAN,

    COUNTRIES.SOUTH_KOREA,

    COUNTRIES.INDIA,

    COUNTRIES.INDONESIA,
    COUNTRIES.VIETNAM,
    COUNTRIES.THAILAND,
    COUNTRIES.MALAYSIA,
    COUNTRIES.PHILIPPINES,

    COUNTRIES.UNITED_STATES,
    COUNTRIES.BRAZIL,
    COUNTRIES.MEXICO,
    COUNTRIES.CANADA,
    COUNTRIES.CARIBBEAN,
    COUNTRIES.MALDIVES,
  ],
  GLOBAL: [],
  CMT: [],
  STRATS: [],
}

DEAL_COUNTRY_LIST_BY_TEAM['GIPS'] = uniq([
  ...['Global', 'Americas', 'Europe', 'Asia', 'Greater China'],
  ...DEAL_COUNTRY_LIST_BY_TEAM.ASIG,
  ...DEAL_COUNTRY_LIST_BY_TEAM.EU,
])
