import {
  INDONESIA,
  MALAYSIA,
  PHILIPPINES,
  THAILAND,
  VIETNAM,
  CHINA,
  INDIA,
} from '../COUNTRY_LIST'
import { INDONESIA_CITIES } from './INDONESIA'

import { MALAYSIA_CITIES } from './MALAYSIA'
import { PHILIPPINES_CITIES } from './PHILIPPINES'
import { THAILAND_CITIES } from './THAILAND'
import { VIETNAM_CITIES } from './VIETNAM'
import { CHINA_CITIES } from './CHINA'
import { INDIA_CITIES } from './INDIA'

export const CITY_LIST_BY_COUNTY: Record<string, string[]> = {
  [INDONESIA]: INDONESIA_CITIES,
  [MALAYSIA]: MALAYSIA_CITIES,
  [PHILIPPINES]: PHILIPPINES_CITIES,
  [THAILAND]: THAILAND_CITIES,
  [VIETNAM]: VIETNAM_CITIES,
  [CHINA]: CHINA_CITIES,
  [INDIA]: INDIA_CITIES,
}
