export const TOTAL_GLA_CHART = 'TOTAL_GLA'
export const TOTAL_RENT_CHART = 'TOTAL_RENT'
export const TOTAL_ASSETS_CHART = 'TOTAL_ASSETS'
export const REVERSION_POTENTIAL_CHART = 'REVERSION_POTENTIAL'
export const OCCUPANCY_CHART = 'OCCUPANCY'
export const AVERAGE_WALE = 'AVERAGE_WALE'
export const TENANT_EXPOSURE_CHART_BY_SECTOR = 'TENANT_EXPOSURE_CHART_BY_SECTOR'
export const TENANT_EXPOSURE_CHART_BY_COUNTRY =
  'TENANT_EXPOSURE_CHART_BY_COUNTRY'
export const TENANCY_WALE_PROFILE_CHART_BY_SPACE =
  'TENANCY_WALE_PROFILE_CHART_BY_SPACE'
export const TENANCY_WALE_PROFILE_CHART_BY_RENT =
  'TENANCY_WALE_PROFILE_CHART_BY_RENT'
export const TENANCY_WALE_PROFILE_CHART_BY_PROPERTIES =
  'TENANCY_WALE_PROFILE_CHART_BY_PROPERTIES'

export type ANALYTICS_CHART_TYPE =
  | typeof TOTAL_GLA_CHART
  | typeof TOTAL_RENT_CHART
  | typeof TOTAL_ASSETS_CHART
  | typeof REVERSION_POTENTIAL_CHART
  | typeof OCCUPANCY_CHART
  | typeof AVERAGE_WALE
  | typeof TENANT_EXPOSURE_CHART_BY_SECTOR
  | typeof TENANT_EXPOSURE_CHART_BY_COUNTRY
  | typeof TENANCY_WALE_PROFILE_CHART_BY_SPACE
  | typeof TENANCY_WALE_PROFILE_CHART_BY_RENT
