import {
  MAP_BOUNDARY_SOURCE_ID,
  MARKET_SOURCE_ID,
  HOLDING_SOURCE_ID,
  DIRECTORY_SEARCH_SOURCE_ID,
} from '../sources'

const SourceIds = {
  MAP_BOUNDARY: MAP_BOUNDARY_SOURCE_ID,
  MARKET: MARKET_SOURCE_ID,
  HOLDING: HOLDING_SOURCE_ID,
  SEARCH: DIRECTORY_SEARCH_SOURCE_ID,
}

export default SourceIds
