name: CD UAT

on:
  workflow_dispatch:
    inputs:
      commithash:
        description: "Commit Hash to Deploy (First 7 char)"
        required: true
        default: 'e.g. 69d529e'
        type: string

jobs:
  download-helm-charts:
    uses: gic-actions/artifactory/.github/workflows/download-generic.yml@main
    with:
      commithash: ${{ inputs.commithash }}
      workflowartifactpath: "helmcharts"
    secrets: inherit

  deploy-uat:
    needs: download-helm-charts
    uses: gic-actions/bento/.github/workflows/helm-upgrade-nonprod.yml@main
    with:
      namespace: # input uat namespace
      environment: "uat"
      artifact_name: "helmcharts"
    secrets: inherit
