name: 'OSS'

on:
  pull_request:
    branches: [ "main" ]
  
jobs:
  OSS:
    uses: gic-actions/oss/.github/workflows/dependency-review.yml@main

  create_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
